### ISSUE TITLE
create yurtingress failed

### ISSUE THREAD

**Issue by junfsir** [openyurtio/openyurt#1043] opened 2022-10-31 06:22 UTC
**What happened**: create yurtingress failed

**What you expected to happen**: create yurtingress success

**How to reproduce it (as minimally and precisely as possible)**:  create yurtingress in openyurt v1
cat <<EOF|kubectl apply -f -
apiVersion: apps.openyurt.io/v1alpha1
kind: YurtIngress
metadata:
  name: yurtingress
spec:
    ingressControllerReplicasPerPool: 1
    pools:
      - name: edge02
      - name: edge01
 EOF

**Anything else we need to know?**:

**Environment**: 
- OpenYurt version: v1.0
- Kubernetes version (use `kubectl version`): v1.20.15
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.9.2009 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-1160.45.1.el7.x86_64
- Install tools:
- Others:

I1031 06:03:16.095043       1 yurtingress_controller.go:122] Reconcile YurtIngress: yurtingress
I1031 06:03:16.102354       1 yurtingress_controller.go:151] added pool list is [{edge02 []} {edge01 []}]
I1031 06:03:16.102401       1 apply_addons.go:47] fail get yurt-app-manager role: ClusterRole.rbac.authorization.k8s.io "yurt-app-manager-role" not found
E1031 06:03:16.105038       1 apply_addons.go:64] fail to create the namespace/ingress-nginx: Namespace "ingress-nginx" is invalid: [metadata.ownerReferences.apiVersion: Invalid value: "": version must not be empty, metadata.ownerReferences.kind: Invalid value: "": kind must not be empty, metadata.ownerReferences.name: Invalid value: "": name must not be empty, metadata.ownerReferences.uid: Invalid value: "": uid must not be empty]
2022-10-31T06:03:16.105Z	ERROR	controller.yurtingress-controller	Reconciler error	{"name": "yurtingress", "namespace": "", "error": "fail to create the namespace/ingress-nginx: Namespace \"ingress-nginx\" is invalid: [metadata.ownerReferences.apiVersion: Invalid value: \"\": version must not be empty, metadata.ownerReferences.kind: Invalid value: \"\": kind must not be empty, metadata.ownerReferences.name: Invalid value: \"\": name must not be empty, metadata.ownerReferences.uid: Invalid value: \"\": uid must not be empty]"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:227
/kind bug

**Comment by rambohe-ch** [comment] 2022-10-31 06:51
@zzguang PTAL

**Comment by zzguang** [comment] 2022-10-31 09:15
@junfsir, Please help to check whether the cluster role "yurt-app-manager-role" exists or not.
yurtingress together with yurtappset/yurtappdaemon depends on this cluster role to operate the related resources.
If it doesn't exist in the cluster, we should nail down the root cause of it firstly.

**Comment by junfsir** [comment] 2022-10-31 10:34
@zzguang "yurt-app-manager-role"  doesn't exist, but cluster role "yurt-app-manager"  does.
```
~]# kubectl get clusterrole|grep yurt-app-manager
yurt-app-manager                                                       2022-10-27T09:25:53Z
~]# helm list -n kube-system
NAME            	NAMESPACE  	REVISION	UPDATED                                	STATUS  	CHART                 	APP VERSION
openyurt        	kube-system	1       	2022-10-27 17:27:13.888798547 +0800 CST	deployed	openyurt-1.0.2        	1.0.0
yurt-app-manager	kube-system	1       	2022-10-27 17:25:37.001929711 +0800 CST	deployed	yurt-app-manager-0.1.3	0.6.0
```

**Comment by zzguang** [comment] 2022-10-31 12:34
> @zzguang "yurt-app-manager-role" doesn't exist, but cluster role "yurt-app-manager" does.
> 
> ```
> ~]# kubectl get clusterrole|grep yurt-app-manager
> yurt-app-manager                                                       2022-10-27T09:25:53Z
> ~]# helm list -n kube-system
> NAME            	NAMESPACE  	REVISION	UPDATED                                	STATUS  	CHART                 	APP VERSION
> openyurt        	kube-system	1       	2022-10-27 17:27:13.888798547 +0800 CST	deployed	openyurt-1.0.2        	1.0.0
> yurt-app-manager	kube-system	1       	2022-10-27 17:25:37.001929711 +0800 CST	deployed	yurt-app-manager-0.1.3	0.6.0
> ```

Thanks, it seems some previous PR led to this regression for renaming this cluster role, you can rename this cluster role to yurt-app-manager-role and verify whether yurtingress CR can be created successfully, we will check the details and fix it later.

**Comment by junfsir** [comment] 2022-11-01 00:44
@zzguang I created a new cluster role named "yurt-app-manager-role", and after applied the "yurtingress" yaml, another error occurred.
```
apiVersion: apps.openyurt.io/v1alpha1
kind: YurtIngress
metadata:
  name: yurtingress
spec:
    ingressControllerReplicasPerPool: 1
    ingressControllerImage: k8s.gcr.io/ingress-nginx/controller:v0.49.0
    ingressWebhookCertGenImage: k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v0.49.0
    pools:
      - name: edge02
      - name: edge01
```
```
I1101 00:36:28.737014       1 yurtingress_controller.go:122] Reconcile YurtIngress: yurtingress
I1101 00:36:28.741046       1 yurtingress_controller.go:151] added pool list is [{edge02 []} {edge01 []}]
E1101 00:36:28.745867       1 apply_addons.go:206] fail to create the deployment/edge02-ingress-nginx-controller: Deployment.apps "edge02-ingress-nginx-controller" is invalid: spec.template.spec.containers[0].image: Required value
2022-11-01T00:36:28.745Z	ERROR	controller.yurtingress-controller	Reconciler error	{"name": "yurtingress", "namespace": "", "error": "fail to create the deployment/edge02-ingress-nginx-controller: Deployment.apps \"edge02-ingress-nginx-controller\" is invalid: spec.template.spec.containers[0].image: Required value"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:227
```

**Comment by zzguang** [comment] 2022-11-01 07:55
@junfsir , some previous PR didn't make a consistent optimization which led to YurtIngress CR creation failure, @huiwq1990 has submitted a reconstruction PR to optimize yurtingress implementation from yaml file to helm chart: https://github.com/openyurtio/yurt-app-manager/pull/124,  
when this PR is merged, you can check whether this issue is fixed, thanks!

**Closed** 2023-01-30 09:49 UTC
Labels: kind/bug, wontfix
